# Generated by Django 5.1.3 on 2025-05-11 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_activation_email_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='activation_email_count',
            new_name='activation_attempts',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_activation_email_sent',
            new_name='last_activation_sent',
        ),
    ]
