# Generated by Django 5.1.3 on 2025-05-11 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_activation_email_count_account_activation_attempts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_activation_sent',
            new_name='activation_sent_at',
        ),
    ]
