# Generated by Django 5.1.3 on 2025-05-11 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_last_activation_sent_account_activation_sent_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='activation_sent_at',
            new_name='last_activation_sent',
        ),
    ]
