# Generated by Django 5.1.3 on 2025-05-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_activation_sent_at_account_last_activation_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activation_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
